sample_app-master/config/routes.rb
Rails.application.routes.draw do

  #get 'sessions/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help', as: 'help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/new', to: 'users#new' #注册
  get '/login', to: 'sessions#new' #登录
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  #get '/mine',  to: 'users#mine' #个人页面

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :weibos, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :talks do
    member do
      get :talking, :talked
    end
  end

end

sample_app-master/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      错误数量 <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

sample_app-master/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="weibos">
    <%= render @feed_items %>

  </ol>
  <%= will_paginate @feed_items %>
<% end %>

sample_app-master/app/views/shared/_pl.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= talking_talk_path(@user.weibos) %>">
    <strong id="talking" class="stat">
      <%#= @talk.talking.count %>
    </strong>
    我的评论
  </a>
  <a href="<%= talked_talk_path(@user.weibos) %>">
    <strong id="talked" class="stat">
      <%#= @talk.talked.count %>
    </strong>
    评论我的
  </a>
</div>

sample_app-master/app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    我的关注
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    我的粉丝
  </a>
</div>

sample_app-master/app/views/shared/_talk_from.html.erb
<%= form_for(@talk) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "分享你的评论..."%>
  </div>
  <%= f.hidden_field :weibo_id %>

  <%= f.submit "发布", class: "btn btn-primary" %>
<% end %>

sample_app-master/app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<img src="/assets/svg.jpeg" style="display: block;width: 100px;height: 100px"><br>

<h1><%= current_user.name %></h1>
<span><%= link_to "查看我的主页", current_user %></span>
<span><%= current_user.weibos.count%>条微博</span>
<!--<img src="assets/svg.jpeg" style="display: block;width: 100px;height: 100px">-->

sample_app-master/app/views/shared/_weibo_form.html.erb
<%= form_for(@weibo) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "分享今天的新鲜事..." %>
  </div>
  <%= f.submit "发布", class: "btn btn-primary" %>
<% end %>